name: Publish Python SDK
on: workflow_dispatch
permissions:
  contents: read
  id-token: write
jobs:
  publish:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - run: python3 -m venv .venv
      - run: .venv/bin/python -m unittest discover -s packages/sdk-python
      - run: .venv/bin/python -m pip install build
      - run: .venv/bin/python -m build packages/sdk-python
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33
        with:
          packages-dir: packages/sdk-python/dist/
